-- MySQL Script generated by MySQL Workbench
-- Fri May 12 00:12:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shorter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shorter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shorter` DEFAULT CHARACTER SET utf8 ;
USE `shorter` ;

-- -----------------------------------------------------
-- Table `shorter`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shorter`.`author` (
  `id` VARCHAR(128) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `created_at` INT NOT NULL,
  `key` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shorter`.`sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shorter`.`sheet` (
  `id` VARCHAR(128) NOT NULL,
  `created_at` INT NOT NULL,
  `type` VARCHAR(32) NOT NULL,
  `text` TEXT(1024) NOT NULL,
  `link` TEXT(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `created_at` (`created_at` ASC),
  CONSTRAINT `author`
    FOREIGN KEY (`id`)
    REFERENCES `shorter`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
